import "./globals.css";
import { Rubik } from 'next/font/google'

export const rubik = Rubik({
  subsets: ['latin'],
  weight: ['400', '500', '700'], // Customize as needed
  variable: '--font-rubik',      // Optional for Tailwind
})

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`antialiased ${rubik.variable}`}
      >
        {children}
      </body>
    </html>
  );
}
